[project]
name = "pcl-rustic"
version = "0.1.0"
description = "高性能Python点云运算库 - 基于Rust burn张量的批量运算"
readme = "README.md"
authors = [
    { name = "liuzhen19", email = "liuzhen19@xiaomi.com" }
]
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "numpy>=2.0.0",
    "pytest-cov>=7.0.0",
]



[tool.maturin]
module-name = "pcl_rustic._core"
python-packages = ["pcl_rustic"]
python-source = "src"
features = ["pyo3/extension-module"]

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "src/**/*.rs" }, { file = "Cargo.toml" }, { file = "Cargo.lock" }]

[[tool.uv.index]]
url = "https://pkgs.d.xiaomi.net/artifactory/api/pypi/pypi-virtual/simple"
default = true

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "laspy>=2.7.0",
    "loguru>=0.7.3",
    "maturin>=1.13.1",
    "pytest>=8.4.2",
]
docs = [
    "mkdocs-material>=9.5.0",
    "mkdocs-git-revision-date-localized-plugin>=1.2.0",
]
benchmark = [
    "open3d>=0.18.0",
    "plotly>=5.24.0",
    "pytest-benchmark>=5.0.0",
]
