from typing import Any, Dict, List, Optional, Tuple

import numpy as np
from numpy.typing import NDArray

NumericArray = NDArray[Any]

class PointCloud:
    def __new__(cls) -> "PointCloud": ...
    @staticmethod
    def from_xyz(xyz: NumericArray) -> "PointCloud": ...
    @staticmethod
    def from_xyz_intensity(xyz: NumericArray, intensity: NumericArray) -> "PointCloud": ...
    @staticmethod
    def from_xyz_rgb(
        xyz: NumericArray, r: NumericArray, g: NumericArray, b: NumericArray
    ) -> "PointCloud": ...
    @staticmethod
    def from_numpy(data: Dict[str, NumericArray]) -> "PointCloud": ...
    @staticmethod
    def from_dict(data: Dict[str, NumericArray]) -> "PointCloud": ...
    @staticmethod
    def from_las(path: str) -> "PointCloud": ...
    @staticmethod
    def concatenate(clouds: List["PointCloud"], policy: str = "strict") -> "PointCloud": ...
    @staticmethod
    def delete_file(path: str) -> None: ...
    def point_count(self) -> int: ...
    def get_xyz(self) -> NDArray[np.float32]: ...
    def to_dict(self) -> Dict[str, NumericArray]: ...
    def clone(self) -> "PointCloud": ...
    def has_intensity(self) -> bool: ...
    def has_rgb(self) -> bool: ...
    def get_intensity(self) -> Optional[NumericArray]: ...
    def get_rgb(self) -> Optional[Tuple[NumericArray, NumericArray, NumericArray]]: ...
    def set_intensity(self, intensity: NumericArray) -> None: ...
    def set_rgb(self, r: NumericArray, g: NumericArray, b: NumericArray) -> None: ...
    def set_attribute(self, name: str, data: NumericArray) -> None: ...
    def add_attribute(self, name: str, data: NumericArray) -> None: ...
    def get_attribute(self, name: str) -> Optional[NumericArray]: ...
    def attribute_names(self) -> List[str]: ...
    def attribute_info(self) -> List[Tuple[str, int, str]]: ...
    def remove_attribute(self, name: str) -> None: ...
    def clear_attributes(self) -> None: ...
    def has_attributes(self, names: List[str]) -> bool: ...
    def remove_intensity(self) -> None: ...
    def remove_rgb(self) -> None: ...
    def transform(self, matrix: NumericArray) -> "PointCloud": ...
    def rigid_transform(self, rotation: NumericArray, translation: NumericArray) -> "PointCloud": ...
    def translate(self, t: NumericArray) -> "PointCloud": ...
    def scale(self, s: float, center: Optional[NumericArray] = None) -> "PointCloud": ...
    def rotate(self, rotation: NumericArray, center: Optional[NumericArray] = None) -> "PointCloud": ...
    def voxel_downsample(
        self, voxel_size: float, strategy: int = 1, seed: Optional[int] = None
    ) -> "PointCloud": ...
    def select(self, mask: NDArray[np.bool_]) -> "PointCloud": ...
    def select_indices(self, indices: List[int]) -> "PointCloud": ...
    def select_where(
        self, name: str, op: str, values: List[float], inclusive: bool = True
    ) -> "PointCloud": ...
    def select_by_classification(self, codes: List[int]) -> "PointCloud": ...
    def select_intensity_range(self, lo: float, hi: float) -> "PointCloud": ...
    def select_return_number(self, n: int) -> "PointCloud": ...
    def select_elevation_range(self, lo: float, hi: float) -> "PointCloud": ...
    def crop_aabb(self, min: NumericArray, max: NumericArray) -> "PointCloud": ...
    def aabb(self) -> Tuple[Tuple[float, float, float], Tuple[float, float, float]]: ...
    def crop_obb(
        self, center: NumericArray, extents: NumericArray, rotation: NumericArray
    ) -> "PointCloud": ...
    def obb(
        self,
    ) -> Tuple[
        Tuple[float, float, float],
        Tuple[float, float, float],
        Tuple[Tuple[float, float, float], Tuple[float, float, float], Tuple[float, float, float]],
    ]: ...
    def knn(self, query: NumericArray, k: int) -> Tuple[NDArray[np.int64], NDArray[np.float32]]: ...
    def radius_search(self, query: NumericArray, radius: float) -> List[NDArray[np.int64]]: ...
    def estimate_normals(self, search: "NormalSearch") -> None: ...
    def estimate_covariances(self, knn: int) -> None: ...
    def remove_statistical_outlier(
        self, nb_neighbors: int, std_ratio: float
    ) -> Tuple["PointCloud", NDArray[np.bool_]]: ...
    def remove_radius_outlier(
        self, nb_points: int, radius: float
    ) -> Tuple["PointCloud", NDArray[np.bool_]]: ...
    def octree(self, max_depth: int) -> "Octree": ...
    def to(self, device: str) -> "PointCloud": ...
    def device(self) -> str: ...
    def to_las(self, path: str, compress: bool = False) -> None: ...
    def memory_usage(self) -> int: ...
    def __repr__(self) -> str: ...

class DownsampleStrategy:
    RANDOM_SEEDED: int
    NEAREST_TO_CENTROID: int
    AVERAGE: int
    RANDOM: int
    CENTROID: int

class NormalSearch:
    @staticmethod
    def knn(k: int) -> "NormalSearch": ...
    @staticmethod
    def radius(radius: float) -> "NormalSearch": ...
    @staticmethod
    def hybrid(radius: float, k: int) -> "NormalSearch": ...

class Octree:
    def range_search(self, center: NumericArray, radius: float) -> List[int]: ...
    def voxel_centers(self) -> NDArray[np.float32]: ...

class ICPConvergenceCriteria:
    def __new__(
        cls,
        max_iteration: int = 30,
        relative_fitness: float = 1e-6,
        relative_rmse: float = 1e-6,
    ) -> "ICPConvergenceCriteria": ...

class TransformationEstimation:
    @staticmethod
    def point_to_point() -> "TransformationEstimation": ...
    @staticmethod
    def point_to_plane() -> "TransformationEstimation": ...
    @staticmethod
    def generalized(epsilon: float = 1e-3) -> "TransformationEstimation": ...

class RegistrationResult:
    @property
    def transformation(self) -> NDArray[np.float32]: ...
    @property
    def fitness(self) -> float: ...
    @property
    def inlier_rmse(self) -> float: ...
    @property
    def correspondence_set(self) -> List[Tuple[int, int]]: ...

class registration:
    ICPConvergenceCriteria: type[ICPConvergenceCriteria]
    TransformationEstimation: type[TransformationEstimation]
    RegistrationResult: type[RegistrationResult]
    @staticmethod
    def icp(
        source: PointCloud,
        target: PointCloud,
        max_correspondence_distance: float,
        init: NumericArray,
        estimation: Optional[TransformationEstimation] = None,
        criteria: Optional[ICPConvergenceCriteria] = None,
    ) -> RegistrationResult: ...
    @staticmethod
    def evaluate(
        source: PointCloud,
        target: PointCloud,
        max_correspondence_distance: float,
        transformation: NumericArray,
    ) -> RegistrationResult: ...
